// SPDX-FileCopyrightText: Copyright 2024 The Minder Authors
// SPDX-License-Identifier: Apache-2.0

// This file contains definitions for entities which are created automatically
// by Minder (as descendants of entities managed via the public APIs).
// At the moment, this is primarily pull requests and selectors, but may
// include other resources whose lifetime is managed automatically later.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: minder/entities/internal.proto

// buf:lint:ignore PACKAGE_VERSION_SUFFIX

package entities

import (
	v1 "github.com/mindersec/minder/pkg/api/protobuf/go/minder/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DepEcosystem int32

const (
	DepEcosystem_DEP_ECOSYSTEM_UNSPECIFIED DepEcosystem = 0
	DepEcosystem_DEP_ECOSYSTEM_NPM         DepEcosystem = 1
	DepEcosystem_DEP_ECOSYSTEM_GO          DepEcosystem = 2
	DepEcosystem_DEP_ECOSYSTEM_PYPI        DepEcosystem = 3
)

// Enum value maps for DepEcosystem.
var (
	DepEcosystem_name = map[int32]string{
		0: "DEP_ECOSYSTEM_UNSPECIFIED",
		1: "DEP_ECOSYSTEM_NPM",
		2: "DEP_ECOSYSTEM_GO",
		3: "DEP_ECOSYSTEM_PYPI",
	}
	DepEcosystem_value = map[string]int32{
		"DEP_ECOSYSTEM_UNSPECIFIED": 0,
		"DEP_ECOSYSTEM_NPM":         1,
		"DEP_ECOSYSTEM_GO":          2,
		"DEP_ECOSYSTEM_PYPI":        3,
	}
)

func (x DepEcosystem) Enum() *DepEcosystem {
	p := new(DepEcosystem)
	*p = x
	return p
}

func (x DepEcosystem) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DepEcosystem) Descriptor() protoreflect.EnumDescriptor {
	return file_minder_entities_internal_proto_enumTypes[0].Descriptor()
}

func (DepEcosystem) Type() protoreflect.EnumType {
	return &file_minder_entities_internal_proto_enumTypes[0]
}

func (x DepEcosystem) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DepEcosystem.Descriptor instead.
func (DepEcosystem) EnumDescriptor() ([]byte, []int) {
	return file_minder_entities_internal_proto_rawDescGZIP(), []int{0}
}

type Dependency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ecosystem     DepEcosystem           `protobuf:"varint,1,opt,name=ecosystem,proto3,enum=internal.DepEcosystem" json:"ecosystem,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dependency) Reset() {
	*x = Dependency{}
	mi := &file_minder_entities_internal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dependency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dependency) ProtoMessage() {}

func (x *Dependency) ProtoReflect() protoreflect.Message {
	mi := &file_minder_entities_internal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dependency.ProtoReflect.Descriptor instead.
func (*Dependency) Descriptor() ([]byte, []int) {
	return file_minder_entities_internal_proto_rawDescGZIP(), []int{0}
}

func (x *Dependency) GetEcosystem() DepEcosystem {
	if x != nil {
		return x.Ecosystem
	}
	return DepEcosystem_DEP_ECOSYSTEM_UNSPECIFIED
}

func (x *Dependency) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Dependency) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// Internally-lifecycle-managed entity
type PullRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Url       string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`                              // The full URL to the PR
	CommitSha string                 `protobuf:"bytes,2,opt,name=commit_sha,json=commitSha,proto3" json:"commit_sha,omitempty"` // Commit SHA of the PR HEAD. Will be useful to submit a review
	Number    int64                  `protobuf:"varint,3,opt,name=number,proto3" json:"number,omitempty"`                       // The sequential PR number (not the DB PK!)
	RepoOwner string                 `protobuf:"bytes,4,opt,name=repo_owner,json=repoOwner,proto3" json:"repo_owner,omitempty"` // The owner of the repo, will be used to submit a review
	RepoName  string                 `protobuf:"bytes,5,opt,name=repo_name,json=repoName,proto3" json:"repo_name,omitempty"`    // The name of the repo, will be used to submit a review
	AuthorId  int64                  `protobuf:"varint,6,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`   // The author of the PR, will be used to check if we can request changes
	Action    string                 `protobuf:"bytes,7,opt,name=action,proto3" json:"action,omitempty"`                        // The action that triggered the webhook
	Context   *v1.Context            `protobuf:"bytes,8,opt,name=context,proto3" json:"context,omitempty"`
	// properties is a map of properties of the entity.
	Properties     *structpb.Struct `protobuf:"bytes,9,opt,name=properties,proto3" json:"properties,omitempty"`
	BaseCloneUrl   string           `protobuf:"bytes,10,opt,name=base_clone_url,json=baseCloneUrl,proto3" json:"base_clone_url,omitempty"`       // URL used to clone the base repository
	TargetCloneUrl string           `protobuf:"bytes,11,opt,name=target_clone_url,json=targetCloneUrl,proto3" json:"target_clone_url,omitempty"` // URL used to clone the target repository
	BaseRef        string           `protobuf:"bytes,12,opt,name=base_ref,json=baseRef,proto3" json:"base_ref,omitempty"`                        // The base ref of the PR
	TargetRef      string           `protobuf:"bytes,13,opt,name=target_ref,json=targetRef,proto3" json:"target_ref,omitempty"`                  // The target ref of the PR
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PullRequest) Reset() {
	*x = PullRequest{}
	mi := &file_minder_entities_internal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullRequest) ProtoMessage() {}

func (x *PullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minder_entities_internal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullRequest.ProtoReflect.Descriptor instead.
func (*PullRequest) Descriptor() ([]byte, []int) {
	return file_minder_entities_internal_proto_rawDescGZIP(), []int{1}
}

func (x *PullRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PullRequest) GetCommitSha() string {
	if x != nil {
		return x.CommitSha
	}
	return ""
}

func (x *PullRequest) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *PullRequest) GetRepoOwner() string {
	if x != nil {
		return x.RepoOwner
	}
	return ""
}

func (x *PullRequest) GetRepoName() string {
	if x != nil {
		return x.RepoName
	}
	return ""
}

func (x *PullRequest) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *PullRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PullRequest) GetContext() *v1.Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *PullRequest) GetProperties() *structpb.Struct {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *PullRequest) GetBaseCloneUrl() string {
	if x != nil {
		return x.BaseCloneUrl
	}
	return ""
}

func (x *PullRequest) GetTargetCloneUrl() string {
	if x != nil {
		return x.TargetCloneUrl
	}
	return ""
}

func (x *PullRequest) GetBaseRef() string {
	if x != nil {
		return x.BaseRef
	}
	return ""
}

func (x *PullRequest) GetTargetRef() string {
	if x != nil {
		return x.TargetRef
	}
	return ""
}

// #### internal/engine only
type PrDependencies struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	Pr            *PullRequest                           `protobuf:"bytes,1,opt,name=pr,proto3" json:"pr,omitempty"`
	Deps          []*PrDependencies_ContextualDependency `protobuf:"bytes,2,rep,name=deps,proto3" json:"deps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrDependencies) Reset() {
	*x = PrDependencies{}
	mi := &file_minder_entities_internal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrDependencies) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrDependencies) ProtoMessage() {}

func (x *PrDependencies) ProtoReflect() protoreflect.Message {
	mi := &file_minder_entities_internal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrDependencies.ProtoReflect.Descriptor instead.
func (*PrDependencies) Descriptor() ([]byte, []int) {
	return file_minder_entities_internal_proto_rawDescGZIP(), []int{2}
}

func (x *PrDependencies) GetPr() *PullRequest {
	if x != nil {
		return x.Pr
	}
	return nil
}

func (x *PrDependencies) GetDeps() []*PrDependencies_ContextualDependency {
	if x != nil {
		return x.Deps
	}
	return nil
}

// #### internal/engine only
type PrContents struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pr            *PullRequest           `protobuf:"bytes,1,opt,name=pr,proto3" json:"pr,omitempty"`
	Files         []*PrContents_File     `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrContents) Reset() {
	*x = PrContents{}
	mi := &file_minder_entities_internal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrContents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrContents) ProtoMessage() {}

func (x *PrContents) ProtoReflect() protoreflect.Message {
	mi := &file_minder_entities_internal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrContents.ProtoReflect.Descriptor instead.
func (*PrContents) Descriptor() ([]byte, []int) {
	return file_minder_entities_internal_proto_rawDescGZIP(), []int{3}
}

func (x *PrContents) GetPr() *PullRequest {
	if x != nil {
		return x.Pr
	}
	return nil
}

func (x *PrContents) GetFiles() []*PrContents_File {
	if x != nil {
		return x.Files
	}
	return nil
}

type PrDependencies_ContextualDependency struct {
	state         protoimpl.MessageState                         `protogen:"open.v1"`
	Dep           *Dependency                                    `protobuf:"bytes,1,opt,name=dep,proto3" json:"dep,omitempty"`
	File          *PrDependencies_ContextualDependency_FilePatch `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrDependencies_ContextualDependency) Reset() {
	*x = PrDependencies_ContextualDependency{}
	mi := &file_minder_entities_internal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrDependencies_ContextualDependency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrDependencies_ContextualDependency) ProtoMessage() {}

func (x *PrDependencies_ContextualDependency) ProtoReflect() protoreflect.Message {
	mi := &file_minder_entities_internal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrDependencies_ContextualDependency.ProtoReflect.Descriptor instead.
func (*PrDependencies_ContextualDependency) Descriptor() ([]byte, []int) {
	return file_minder_entities_internal_proto_rawDescGZIP(), []int{2, 0}
}

func (x *PrDependencies_ContextualDependency) GetDep() *Dependency {
	if x != nil {
		return x.Dep
	}
	return nil
}

func (x *PrDependencies_ContextualDependency) GetFile() *PrDependencies_ContextualDependency_FilePatch {
	if x != nil {
		return x.File
	}
	return nil
}

type PrDependencies_ContextualDependency_FilePatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                         // file changed, e.g. package-lock.json
	PatchUrl      string                 `protobuf:"bytes,2,opt,name=patch_url,json=patchUrl,proto3" json:"patch_url,omitempty"` // points to the the raw patchfile
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrDependencies_ContextualDependency_FilePatch) Reset() {
	*x = PrDependencies_ContextualDependency_FilePatch{}
	mi := &file_minder_entities_internal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrDependencies_ContextualDependency_FilePatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrDependencies_ContextualDependency_FilePatch) ProtoMessage() {}

func (x *PrDependencies_ContextualDependency_FilePatch) ProtoReflect() protoreflect.Message {
	mi := &file_minder_entities_internal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrDependencies_ContextualDependency_FilePatch.ProtoReflect.Descriptor instead.
func (*PrDependencies_ContextualDependency_FilePatch) Descriptor() ([]byte, []int) {
	return file_minder_entities_internal_proto_rawDescGZIP(), []int{2, 0, 0}
}

func (x *PrDependencies_ContextualDependency_FilePatch) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PrDependencies_ContextualDependency_FilePatch) GetPatchUrl() string {
	if x != nil {
		return x.PatchUrl
	}
	return ""
}

type PrContents_File struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Name          string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FilePatchUrl  string                  `protobuf:"bytes,2,opt,name=file_patch_url,json=filePatchUrl,proto3" json:"file_patch_url,omitempty"`
	PatchLines    []*PrContents_File_Line `protobuf:"bytes,3,rep,name=patch_lines,json=patchLines,proto3" json:"patch_lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrContents_File) Reset() {
	*x = PrContents_File{}
	mi := &file_minder_entities_internal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrContents_File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrContents_File) ProtoMessage() {}

func (x *PrContents_File) ProtoReflect() protoreflect.Message {
	mi := &file_minder_entities_internal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrContents_File.ProtoReflect.Descriptor instead.
func (*PrContents_File) Descriptor() ([]byte, []int) {
	return file_minder_entities_internal_proto_rawDescGZIP(), []int{3, 0}
}

func (x *PrContents_File) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PrContents_File) GetFilePatchUrl() string {
	if x != nil {
		return x.FilePatchUrl
	}
	return ""
}

func (x *PrContents_File) GetPatchLines() []*PrContents_File_Line {
	if x != nil {
		return x.PatchLines
	}
	return nil
}

type PrContents_File_Line struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deliberately left as an int32: a diff with more than 2^31 lines
	// could lead to various problems while processing.
	LineNumber    int32  `protobuf:"varint,1,opt,name=line_number,json=lineNumber,proto3" json:"line_number,omitempty"`
	Content       string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrContents_File_Line) Reset() {
	*x = PrContents_File_Line{}
	mi := &file_minder_entities_internal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrContents_File_Line) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrContents_File_Line) ProtoMessage() {}

func (x *PrContents_File_Line) ProtoReflect() protoreflect.Message {
	mi := &file_minder_entities_internal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrContents_File_Line.ProtoReflect.Descriptor instead.
func (*PrContents_File_Line) Descriptor() ([]byte, []int) {
	return file_minder_entities_internal_proto_rawDescGZIP(), []int{3, 0, 0}
}

func (x *PrContents_File_Line) GetLineNumber() int32 {
	if x != nil {
		return x.LineNumber
	}
	return 0
}

func (x *PrContents_File_Line) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_minder_entities_internal_proto protoreflect.FileDescriptor

const file_minder_entities_internal_proto_rawDesc = "" +
	"\n" +
	"\x1eminder/entities/internal.proto\x12\binternal\x1a\x16minder/v1/minder.proto\x1a\x1cgoogle/protobuf/struct.proto\"p\n" +
	"\n" +
	"Dependency\x124\n" +
	"\tecosystem\x18\x01 \x01(\x0e2\x16.internal.DepEcosystemR\tecosystem\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"\xb8\x03\n" +
	"\vPullRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"commit_sha\x18\x02 \x01(\tR\tcommitSha\x12\x16\n" +
	"\x06number\x18\x03 \x01(\x03R\x06number\x12\x1d\n" +
	"\n" +
	"repo_owner\x18\x04 \x01(\tR\trepoOwner\x12\x1b\n" +
	"\trepo_name\x18\x05 \x01(\tR\brepoName\x12\x1b\n" +
	"\tauthor_id\x18\x06 \x01(\x03R\bauthorId\x12\x16\n" +
	"\x06action\x18\a \x01(\tR\x06action\x12,\n" +
	"\acontext\x18\b \x01(\v2\x12.minder.v1.ContextR\acontext\x127\n" +
	"\n" +
	"properties\x18\t \x01(\v2\x17.google.protobuf.StructR\n" +
	"properties\x12$\n" +
	"\x0ebase_clone_url\x18\n" +
	" \x01(\tR\fbaseCloneUrl\x12(\n" +
	"\x10target_clone_url\x18\v \x01(\tR\x0etargetCloneUrl\x12\x19\n" +
	"\bbase_ref\x18\f \x01(\tR\abaseRef\x12\x1d\n" +
	"\n" +
	"target_ref\x18\r \x01(\tR\ttargetRef\"\xc6\x02\n" +
	"\x0ePrDependencies\x12%\n" +
	"\x02pr\x18\x01 \x01(\v2\x15.internal.PullRequestR\x02pr\x12A\n" +
	"\x04deps\x18\x02 \x03(\v2-.internal.PrDependencies.ContextualDependencyR\x04deps\x1a\xc9\x01\n" +
	"\x14ContextualDependency\x12&\n" +
	"\x03dep\x18\x01 \x01(\v2\x14.internal.DependencyR\x03dep\x12K\n" +
	"\x04file\x18\x02 \x01(\v27.internal.PrDependencies.ContextualDependency.FilePatchR\x04file\x1a<\n" +
	"\tFilePatch\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tpatch_url\x18\x02 \x01(\tR\bpatchUrl\"\xab\x02\n" +
	"\n" +
	"PrContents\x12%\n" +
	"\x02pr\x18\x01 \x01(\v2\x15.internal.PullRequestR\x02pr\x12/\n" +
	"\x05files\x18\x02 \x03(\v2\x19.internal.PrContents.FileR\x05files\x1a\xc4\x01\n" +
	"\x04File\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12$\n" +
	"\x0efile_patch_url\x18\x02 \x01(\tR\ffilePatchUrl\x12?\n" +
	"\vpatch_lines\x18\x03 \x03(\v2\x1e.internal.PrContents.File.LineR\n" +
	"patchLines\x1aA\n" +
	"\x04Line\x12\x1f\n" +
	"\vline_number\x18\x01 \x01(\x05R\n" +
	"lineNumber\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent*r\n" +
	"\fDepEcosystem\x12\x1d\n" +
	"\x19DEP_ECOSYSTEM_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11DEP_ECOSYSTEM_NPM\x10\x01\x12\x14\n" +
	"\x10DEP_ECOSYSTEM_GO\x10\x02\x12\x16\n" +
	"\x12DEP_ECOSYSTEM_PYPI\x10\x03BAZ?github.com/mindersec/minder/pkg/api/protobuf/go/minder/entitiesb\x06proto3"

var (
	file_minder_entities_internal_proto_rawDescOnce sync.Once
	file_minder_entities_internal_proto_rawDescData []byte
)

func file_minder_entities_internal_proto_rawDescGZIP() []byte {
	file_minder_entities_internal_proto_rawDescOnce.Do(func() {
		file_minder_entities_internal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_minder_entities_internal_proto_rawDesc), len(file_minder_entities_internal_proto_rawDesc)))
	})
	return file_minder_entities_internal_proto_rawDescData
}

var file_minder_entities_internal_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_minder_entities_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_minder_entities_internal_proto_goTypes = []any{
	(DepEcosystem)(0),                                     // 0: internal.DepEcosystem
	(*Dependency)(nil),                                    // 1: internal.Dependency
	(*PullRequest)(nil),                                   // 2: internal.PullRequest
	(*PrDependencies)(nil),                                // 3: internal.PrDependencies
	(*PrContents)(nil),                                    // 4: internal.PrContents
	(*PrDependencies_ContextualDependency)(nil),           // 5: internal.PrDependencies.ContextualDependency
	(*PrDependencies_ContextualDependency_FilePatch)(nil), // 6: internal.PrDependencies.ContextualDependency.FilePatch
	(*PrContents_File)(nil),                               // 7: internal.PrContents.File
	(*PrContents_File_Line)(nil),                          // 8: internal.PrContents.File.Line
	(*v1.Context)(nil),                                    // 9: minder.v1.Context
	(*structpb.Struct)(nil),                               // 10: google.protobuf.Struct
}
var file_minder_entities_internal_proto_depIdxs = []int32{
	0,  // 0: internal.Dependency.ecosystem:type_name -> internal.DepEcosystem
	9,  // 1: internal.PullRequest.context:type_name -> minder.v1.Context
	10, // 2: internal.PullRequest.properties:type_name -> google.protobuf.Struct
	2,  // 3: internal.PrDependencies.pr:type_name -> internal.PullRequest
	5,  // 4: internal.PrDependencies.deps:type_name -> internal.PrDependencies.ContextualDependency
	2,  // 5: internal.PrContents.pr:type_name -> internal.PullRequest
	7,  // 6: internal.PrContents.files:type_name -> internal.PrContents.File
	1,  // 7: internal.PrDependencies.ContextualDependency.dep:type_name -> internal.Dependency
	6,  // 8: internal.PrDependencies.ContextualDependency.file:type_name -> internal.PrDependencies.ContextualDependency.FilePatch
	8,  // 9: internal.PrContents.File.patch_lines:type_name -> internal.PrContents.File.Line
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_minder_entities_internal_proto_init() }
func file_minder_entities_internal_proto_init() {
	if File_minder_entities_internal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_minder_entities_internal_proto_rawDesc), len(file_minder_entities_internal_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_minder_entities_internal_proto_goTypes,
		DependencyIndexes: file_minder_entities_internal_proto_depIdxs,
		EnumInfos:         file_minder_entities_internal_proto_enumTypes,
		MessageInfos:      file_minder_entities_internal_proto_msgTypes,
	}.Build()
	File_minder_entities_internal_proto = out.File
	file_minder_entities_internal_proto_goTypes = nil
	file_minder_entities_internal_proto_depIdxs = nil
}
