# SPDX-FileCopyrightText: Copyright 2023 The Minder Authors
# SPDX-License-Identifier: Apache-2.0
{{ if .Values.routes.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: "{{- .Values.routes.name }}"
  labels:
    {{ include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
spec:
  parentRefs:
    {{- if .Values.routes.parentRefs }}
    {{- toYaml .Values.routes.parentRefs | nindent 4 }}
    {{- end }}
  hostnames:
    - "{{ .Values.hostname }}"
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: minder-grpc
      port: !!int "{{ .Values.service.grpcPort }}"
      weight: 1
    # Envoy-Gateway requires that the matches be non-empty to match GRPC, but allows for regex matches.
    matches:
    - method:
        type: RegularExpression
        service: ".*"
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: "{{- .Values.routes.name }}"
  labels:
    {{ include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
spec:
  parentRefs:
    {{- if .Values.routes.parentRefs }}
    {{- toYaml .Values.routes.parentRefs | nindent 4 }}
    {{- end }}
  hostnames:
    - "{{ .Values.hostname }}"
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: minder-http
      port: !!int "{{ .Values.service.httpPort }}"
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
{{ end }}